### ISSUE TITLE
Fails as the package module does not update cache "name: Install python-pip" task

### ISSUE THREAD

**Issue by aswadrangnekar** [atosatto/ansible-dockerswarm#10]
while running playbook, it fails at https://github.com/atosatto/ansible-dockerswarm/blob/master/tasks/main.yml#L9 as the cache was not updated.

**Comment by aswadrangnekar** [comment]
@atosatto Please take a look at the quick-fix https://github.com/aswadrangnekar/ansible-dockerswarm/commit/36973198537720baeba3e33da4d11f8b322e475b.

Thanks for this repo!

**Comment by atosatto** [comment]
Closing it since PR #11 has been merged!
