### ISSUE TITLE
Unable to provision with Vagrant+ansible

### ISSUE THREAD

**Issue by djalexd** [atosatto/ansible-dockerswarm#15]
Trying to produce a working Vagrant setup, but it consistently fails on:
`./roles/atosatto.docker-swarm/tasks/swarm_cluster.yml#37`
with message:
`the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'docker_manager_address`

I'm not an Ansible expert, but I think the `set_fact` task called `Distribute the fact containing address of the first Swarm manager.` is properly run only with a proper facts inventory (afaik able to build such an inventory on cloud providers, but not via Vagrant, where setup is run sequencially).

https://github.com/djalexd/ansible-dockerswarm-vagrant-runtime

Any tips would be great!

**Comment by atosatto** [comment]
Hi @djalexd. I addressed all your question here:
https://github.com/djalexd/ansible-dockerswarm-vagrant-runtime/pull/1

I hope this will help you to build your testing environment and play with Swarm.
