### ISSUE TITLE
update galaxy

### ISSUE THREAD

**Issue by oppianmatt** [atosatto/ansible-dockerswarm#26]
Version in ansible galaxy is missing the swarm_labels stuff. Mind updating it please?

**Comment by atosatto** [comment]
Ehi @oppianmatt, yes I know that it's not (yet) on galaxy.
As a temporary workaround you might want to add 

```
- src: https://github.com/atosatto/ansible-dockerswarm.git
  scm: git
  version: master
name: atosatto.docker-swarm
```

to your `requirements.yml` file.

I will do a new tagged release as soon as I will fix the CI.
I'm currently working on switching to Molecule v2.

**Comment by atosatto** [comment]
Will do it as soon as we get a stable master. Currently we're working on a better way to handle ssh reconnection and on an improved test suite

**Comment by marcos1990** [comment]
really useful ansible role. would love if we got the labels portion also.
+1

**Comment by juanluisbaptiste** [comment]
Hi,

Is the role in galaxy updated with the latest release here ?

Thanks.

**Comment by atosatto** [comment]
Yes, ansible-galaxy has now v2.0.0 of the role.
