### ISSUE TITLE
How to bind daemon to TCP port for remote access.

### ISSUE THREAD

**Issue by timmyers** [atosatto/ansible-dockerswarm#30]
Hi, I am trying to figure out how to have this role configure the docker daemon to bind a to a TCP port for remote access.

I think that maybe once https://github.com/atosatto/ansible-dockerswarm/pull/23 has been merged in, that will allow for the functionality?

Please let me know!  I'm happy to help add documentation or contribute any other way I can.

**Comment by Bessonov** [comment]
@timmyers AFAIK it's not trivial if you want to do that in secure way. I've created a [docker-remote-api](https://github.com/Bessonov/ansible-role-docker-remote-api) role for this tasks. Basically, it generates ca, client and server certificates on local machine, create an remote api image with ca and deploy that image on docker host with ansible. Then you can connect to the docker manager with ca and client certificate.

I didn't tried it with this role together.

**Comment by atosatto** [comment]
@timmyers, v2.0.0 implements support to both custom daemon configurations to be added to the docker.json file and/or override to the default systemd unit for containerd and docker.
