### ISSUE TITLE
SSH daemon killed when using root user as ansible user

### ISSUE THREAD

**Issue by mdacrema** [atosatto/ansible-dockerswarm#32]
If you use root as user for ansible then it will be killed in tasks/docker_group.yml as results of: pkill -u root sshd 

Simple workaround is to add " && service sshd restart" to shell command

**Comment by val-litvak** [comment]
I ran into this issue as well, I ended up just running it as a non-root user instead. @mdacrema your description helped me work-around the issue, thanks!

**Comment by atosatto** [comment]
@mdacrema can you submit a PR with the fix? ;)

**Comment by drymonsoon** [comment]
PR added #34

**Comment by atosatto** [comment]
Thanks!
