### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by Vad1mo** [atosatto/ansible-dockerswarm#36]
Is this repository still maintained? The current state of the repos isn't working, there are a few important PRs open?

**Comment by atosatto** [comment]
Yes it is. What's not working for you? We do have tags for stable releases.

**Comment by atosatto** [comment]
I have merged some of the open PR. They were still pending because of broken CI in most of them. Will try to fix it and release a new stable tag.

**Comment by atosatto** [comment]
And please let me know if there is any other outstanding bug out there preventing this role to be working for you.
