### ISSUE TITLE
Option to choose Docker Version

### ISSUE THREAD

**Issue by Vad1mo** [atosatto/ansible-dockerswarm#37]
As an user of docker swarm in a productive environment I want to be able to select that Docker Version that should be installed. Right now only 17.05 is installed which is not maintained by Docker anymore.

**Comment by atosatto** [comment]
This is related to #31.
You're right, we need to make the installation procedure much more flexible.

**Comment by atosatto** [comment]
Now that #40 has been finally merged, this should be covered by the `docker_package_version` variable.
Thanks for suggesting this enhancement!
