### ISSUE TITLE
Make linux-image-extra-virtual optional install

### ISSUE THREAD

**Issue by rothgar** [atosatto/ansible-dockerswarm#4]
Referencing this task https://github.com/atosatto/ansible-dockerswarm/blob/master/tasks/docker_engine.yml#L21-L25

The linux-image-extra-virtual package is only needed if you use AUFS storage driver and fails to install on some debian flavors. I'm running on raspberry pi and the package isn't available.

Just a suggestion to make the playbook more flexible.

**Comment by atosatto** [comment]
This is a very good suggestions.
Actually, I never tested the playbook on ARM. 
I'm definitively gonna make the `linux-image-extra-virtual`optional.
Thank you!

**Comment by atosatto** [comment]
I just made possible to customize the `docker_dependencies`.

The following playbook should work on a Raspberry Pi
```
- name: "Provision a Docker Swarm Cluster on ARM"
  hosts: all
  roles:
    - { role: atosatto.docker-swarm,
         docker_dependencies: [ ] }
```

**Comment by rothgar** [comment]
Thanks, I'll give it a try tonight.

It may also be nice to separate out the dependencies (installing docker) from setting up swarm. I have my own playbook for installing docker which duplicates steps

**Comment by rothgar** [comment]
That worked for me.
