### ISSUE TITLE
Fails on Module Add w/ Bionic

### ISSUE THREAD

**Issue by benyanke** [atosatto/ansible-dockerswarm#46]
Receives the following errors when creating a swarm on a clean Ubuntu 18.04 server
```
fatal: [hostname]: FAILED! => {"changed": false, "module_stderr": "Shared connection to hostname closed.\r
", "module_stdout": "Traceback (most recent call last):\r
  File \"/home/benyanke/.ansible/tmp/ansible-tmp-1541531946.58-234265249723950/AnsiballZ_apt_repository.py\", line 113, in <module>\r
    _ansiballz_main()\r
  File \"/home/benyanke/.ansible/tmp/ansible-tmp-1541531946.58-234265249723950/AnsiballZ_apt_repository.py\", line 105, in _ansiballz_main\r
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r
  File \"/home/benyanke/.ansible/tmp/ansible-tmp-1541531946.58-234265249723950/AnsiballZ_apt_repository.py\", line 48, in invoke_module\r
    imp.load_module('__main__', mod, module, MOD_DESC)\r
  File \"/tmp/ansible_apt_repository_payload_1RV081/__main__.py\", line 550, in <module>\r
  File \"/tmp/ansible_apt_repository_payload_1RV081/__main__.py\", line 542, in main\r
  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 546, in update\r
    raise FetchFailedException(e)\r
apt.cache.FetchFailedException: E:Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-bionic/InRelease  403  Forbidden [IP: 52.84.67.161 443], E:The repository 'https://apt.dockerproject.org/repo ubuntu-bionic InRelease' is not signed.\r
", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}



```

**Comment by berlinguyinca** [comment]
same issue here. Looks like the project is not really maintained anymore

**Comment by juanluisbaptiste** [comment]
Still happens with disco. How to change the repository? this role is using an old one that is not used anymore, the correct one is:

https://download.docker.com/linux/ubuntu

According to [official install instructions](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-engine---community-1).

I cannot find anywhere the definition of the repository url, the string "dockerproject.org" is not present anywhere.

**Comment by juanluisbaptiste** [comment]
This only happens with the version on ansible galaxy as also mentioned on #43, the code on git works.

It would be nice to have an updated ansible galaxy package.

**Comment by atosatto** [comment]
> It would be nice to have an updated ansible galaxy package.

I've just updated the role on Galaxy tagging a v2.0.0 fixing a bunch of issues that were outstanding since years.
