### ISSUE TITLE
Unable to find any of pip3 to use

### ISSUE THREAD

**Issue by mikeydiamonds** [atosatto/ansible-dockerswarm#57]
after further testing I see there's reasons python-pip was used instead of python3-pip used but I still get this error on Ubuntu 18.04, ansible version 2.8.5
TASK [swarm : Install docker-py.] ***************
fatal: [192.168.0.11]: FAILED! => {"changed": false, "msg": "Unable to find any of pip3 to use. pip needs to be installed."}

**Comment by mikeydiamonds** [comment]
I was trying to use ansible's docker_swarm_service and figured it out. docker-py Python module has been superseded by docker.

**Comment by juanluisbaptiste** [comment]
@mikeydiamonds I'm facing this issue too, could you expand on what you did to fix it ?
