### ISSUE TITLE
How to use swarm labels with dynamic inventory 

### ISSUE THREAD

**Issue by juanluisbaptiste** [atosatto/ansible-dockerswarm#60]
Hi,

I'm using ansible dynamic inventories with AWS. As the ec2.py inventory script creates a group for example for the labels added to an ec2 instance, how can I add swarm labels to that dynamic group ? it seems there is no way to target a host directy when using dynamic inventory.

**Comment by L1ghtman2k** [comment]
Not sure how exactly you are looking to do it, but I just added to host variables. 

Here is an example of how you can do it https://pastebin.com/63QEcnwD

**Comment by juanluisbaptiste** [comment]
Actually it was very easy and you don't need to code any extra stuff, just map the dynmic groups to static groups as described here:

https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html#static-groups-of-dynamic-groups
