### ISSUE TITLE
Update docker-py to docker

### ISSUE THREAD

**Issue by fmotrifork** [atosatto/ansible-dockerswarm#70]
The pip package `docker-py` has been renamed to `docker`
See this page for more info https://github.com/docker/docker-py/issues/1310

This will allow for using the docker_config_module.
https://docs.ansible.com/ansible/latest/modules/docker_config_module.html

Please note that it is not allowed to have both `docker-py` and `docker` installed at the same time.

**Comment by atosatto** [comment]
Thanks @fmotrifork for the heads-up, I've not fixed this in https://github.com/atosatto/ansible-dockerswarm/pull/72.
