### ISSUE TITLE
failing on "gpg' install - ubuntu 16 node

### ISSUE THREAD

**Issue by fabianochagas** [atosatto/ansible-dockerswarm#71]
Hi there!
The role installs the _gpg_ module on debian-like machines, but it seems that for the ubuntu 16 it is the _gnupg_ .

TASK [atosatto.docker-swarm : Install apt-transport-https and gpg if necessary.] ***********************
fatal: [worker01]: FAILED! => {"changed": false, "msg": "No package matching 'gpg' is available"}

![image](https://user-images.githubusercontent.com/15588061/78358456-3a71f800-7581-11ea-90df-33c718337918.png)

**Comment by atosatto** [comment]
Hi @fabianochagas do you have the `gnupg` package already installed on your boxes?
I am thinking that the only solution would be probably either to duplicate this task or to avoid installing gpg.

**Comment by atosatto** [comment]
I might have found a workaround in #73 that will be part of a `v2.2.0` release that I will be tagging as soon as the tests against master are green.
Thanks for reporting this issue!

**Comment by fabianochagas** [comment]
Thanks a lot!
